const tools=[
{slug:'dog-grooming',name:'Dog Grooming Price Calculator',fields:[['Base service','base',40],['Dog size multiplier','size',1.2],['Extra time (hrs)','hours',0.5],['Hourly labour','labour',25],['Consumables','materials',5],['Target margin %','margin',35]],calc:v=>((v.base*v.size)+(v.hours*v.labour)+v.materials)/(1-v.margin/100)},
{slug:'junk-removal',name:'Junk Removal Quote Calculator',fields:[['Dump fee','dump',95],['Crew size','crew',2],['Hours','hours',2.5],['Hourly labour','labour',25],['Travel km','km',28],['Cost per km','kmp',0.45],['Target margin %','margin',35]],calc:v=>(v.dump+(v.crew*v.hours*v.labour)+(v.km*v.kmp))/(1-v.margin/100)},
{slug:'mobile-detailing',name:'Mobile Detailing Quote Calculator',fields:[['Base package','base',60],['Labour hours','hours',2],['Hourly labour','labour',30],['Consumables','materials',15],['Travel km','km',20],['Cost per km','kmp',0.45],['Target margin %','margin',35]],calc:v=>(v.base+(v.hours*v.labour)+v.materials+(v.km*v.kmp))/(1-v.margin/100)},
{slug:'pressure-washing',name:'Pressure Washing Price Calculator',fields:[['Area m²','area',120],['Price per m²','rate',2.5],['Chemicals','chem',20],['Labour hours','hours',3],['Hourly labour','labour',25],['Target margin %','margin',35]],calc:v=>((v.area*v.rate)+v.chem+(v.hours*v.labour))/(1-v.margin/100)},
{slug:'commercial-cleaning',name:'Commercial Cleaning Bid Calculator',fields:[['Area m²','area',400],['Minutes per 100m²','mins',35],['Visits per month','visits',8],['Hourly labour','labour',18],['Monthly supplies','supplies',80],['Target margin %','margin',30]],calc:v=>{const hrs=(v.area/100*v.mins/60)*v.visits;return((hrs*v.labour)+v.supplies)/(1-v.margin/100)}}
];
const root=document.getElementById('tools');
for(const t of tools){const d=document.createElement('section');d.className='tool';d.innerHTML=`<h2>${t.name}</h2><div class='grid'>${t.fields.map(f=>`<label>${f[0]}<input type='number' step='any' data-k='${f[1]}' value='${f[2]}'></label>`).join('')}</div><button>Calculate quote</button><div class='result'></div>`;d.querySelector('button').onclick=()=>{const vals={};d.querySelectorAll('input').forEach(i=>vals[i.dataset.k]=Number(i.value)||0);const out=t.calc(vals);d.querySelector('.result').textContent=`Recommended quote: €${out.toFixed(2)}`};root.appendChild(d)}
