import {test} from 'node:test';import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';import {readFileSync} from 'node:fs';
import {handleQuoteApi,hash,cleanExpiredQuotes} from '../src/quote-api.js';
import {verifyPaidOrder,paymentMode} from '../src/quote-paypal.js';
const schema=readFileSync(new URL('../migrations/0001_quotes.sql',import.meta.url),'utf8');
const id='12345678-1234-1234-1234-123456789012',token='a'.repeat(64),origin='https://test.example';
function dbAdapter(){const db=new DatabaseSync(':memory:');db.exec(schema);const wrap=(sql,args=[])=>({bind(...a){return wrap(sql,a)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return {meta:db.prepare(sql).run(...args)}}});return{prepare:wrap,batch:a=>Promise.all(a.map(x=>x.run())),db};}
async function setup(){const files=new Map([[id+'/final.pdf',new Uint8Array([37,80,68,70,45])]]);const env={QUOTE_DB:dbAdapter(),QUOTE_FILES:{head:async k=>files.has(k),get:async k=>files.has(k)?{body:files.get(k)}:null,delete:async keys=>keys.forEach(k=>files.delete(k)),put:async(k,v)=>files.set(k,v)},QUOTE_LIMITER:{limit:async()=>({success:true})},QUOTE_PAYMENT_MODE:'sandbox',PAYPAL_CLIENT_ID:'test',PAYPAL_CLIENT_SECRET:'test',PAYPAL_MERCHANT_ID:'merchant',PAYPAL_WEBHOOK_ID:'webhook',QUOTE_SUPPORT_EMAIL:'support@example.com'};await env.QUOTE_DB.prepare('INSERT INTO quotes(id,token_hash,created_at,expires_at,quote_json,order_id,status) VALUES(?,?,?,?,?,?,?)').bind(id,await hash(token),Math.floor(Date.now()/1000),Math.floor(Date.now()/1000)+3600,'{}','ORDER1','checkout').run();return{env,files};}
function req(action,{method='GET',auth=token,body,headers={}}={}){return new Request(`${origin}/api/quotes/${id}/${action}`,{method,headers:{Origin:origin,Authorization:'Bearer '+auth,...headers},body:body?JSON.stringify(body):undefined});}
const order=()=>({id:'ORDER1',intent:'CAPTURE',status:'COMPLETED',purchase_units:[{custom_id:id,payee:{merchant_id:'merchant'},amount:{currency_code:'EUR',value:'3.00'},payments:{captures:[{id:'CAPTURE1',status:'COMPLETED',amount:{currency_code:'EUR',value:'3.00'}}]}}]});
test('live payments require an explicit release gate',()=>{assert.equal(paymentMode({QUOTE_PAYMENT_MODE:'live'}),'disabled');assert.equal(paymentMode({QUOTE_PAYMENT_MODE:'sandbox'}),'sandbox');});
test('verify exact order, merchant, amount, currency and capture',()=>{assert.equal(verifyPaidOrder(order(),{id,order_id:'ORDER1'},'merchant'),'CAPTURE1');for(const mutate of [o=>o.purchase_units[0].amount.value='2.99',o=>o.purchase_units[0].payments.captures[0].status='PENDING',o=>o.purchase_units[0].payee.merchant_id='other',o=>o.purchase_units[0].custom_id='other',o=>o.purchase_units[0].payments.captures.push(o.purchase_units[0].payments.captures[0])]){const o=order();mutate(o);assert.throws(()=>verifyPaidOrder(o,{id,order_id:'ORDER1'},'merchant'));}});
test('browser flags, query strings and wrong token cannot unlock downloads',async()=>{const {env}=await setup();assert.equal((await handleQuoteApi(req('download'),env)).status,403);assert.equal((await handleQuoteApi(req('download',{auth:'b'.repeat(64)}),env)).status,404);assert.equal((await handleQuoteApi(new Request(`${origin}/api/quotes/${id}/download?paid=true`),env)).status,404);});
test('verified payment and repeated confirmation fulfil once, download verifies capture',async()=>{const {env}=await setup();const api=async(_e,path)=>path.includes('/captures/')?{id:'CAPTURE1',status:'COMPLETED',amount:{currency_code:'EUR',value:'3.00'}}:order();for(let n=0;n<3;n++)assert.equal((await handleQuoteApi(req('capture',{method:'POST'}),env,{api})).status,200);assert.equal((await env.QUOTE_DB.prepare("SELECT COUNT(*) AS n FROM quote_events WHERE event='quote_payment_verified'").first()).n,1);const r=await handleQuoteApi(req('download'),env,{api});assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store, private');});
test('pending payment and wrong amount do not grant entitlement',async()=>{for(const mutate of [o=>o.status='APPROVED',o=>o.purchase_units[0].amount.value='1.00']){const {env}=await setup();const o=order();mutate(o);await handleQuoteApi(req('capture',{method:'POST'}),env,{api:async()=>o});assert.notEqual((await env.QUOTE_DB.prepare('SELECT status FROM quotes WHERE id=?').bind(id).first()).status,'paid');}});
test('missing PDF prevents capture; timeout reconciles an already completed order',async()=>{const {env,files}=await setup();files.clear();let calls=0;assert.equal((await handleQuoteApi(req('capture',{method:'POST'}),env,{api:async()=>{calls++;return order()}})).status,503);assert.equal(calls,0);});
test('refund capture check blocks download even before webhook arrives',async()=>{const {env}=await setup();await env.QUOTE_DB.prepare("UPDATE quotes SET status='paid',capture_id='CAPTURE1' WHERE id=?").bind(id).run();const r=await handleQuoteApi(req('download'),env,{api:async()=>({id:'CAPTURE1',status:'REFUNDED'})});assert.equal(r.status,403);});
test('webhook rejects missing or invalid provider verification',async()=>{const {env}=await setup();const make=h=>new Request(origin+'/api/quotes/paypal-webhook',{method:'POST',headers:h,body:JSON.stringify({id:'E1'})});assert.equal((await handleQuoteApi(make({}),env)).status,401);const headers=Object.fromEntries(['auth-algo','cert-url','transmission-id','transmission-sig','transmission-time'].map(n=>['paypal-'+n,'x']));assert.equal((await handleQuoteApi(make(headers),env,{api:async()=>({verification_status:'FAILURE'})})).status,401);});
test('CSRF and rate limits reject checkout requests',async()=>{const {env}=await setup();assert.equal((await handleQuoteApi(req('checkout',{method:'POST',headers:{Origin:'https://evil.example'}}),env)).status,403);env.QUOTE_LIMITER.limit=async()=>({success:false});assert.equal((await handleQuoteApi(req('checkout',{method:'POST'}),env)).status,429);});
test('expired quotes lose access and cleanup deletes files and data',async()=>{const {env,files}=await setup();await env.QUOTE_DB.prepare('UPDATE quotes SET expires_at=1 WHERE id=?').bind(id).run();assert.equal((await handleQuoteApi(req('status'),env)).status,404);await cleanExpiredQuotes(env);assert.equal(files.size,0);assert.equal((await env.QUOTE_DB.prepare('SELECT COUNT(*) AS n FROM quotes').first()).n,0);});
test('checkout reuses one provider order on duplicate requests',async()=>{const {env}=await setup();await env.QUOTE_DB.prepare("UPDATE quotes SET order_id=NULL,status='ready' WHERE id=?").bind(id).run();let creates=0;const api=async(_env,path,options)=>{assert.equal(path,'/v2/checkout/orders');assert.equal(options.idempotency,id);assert.equal(options.body.purchase_units[0].amount.value,'3.00');assert.equal(options.body.intent,'CAPTURE');creates++;return{id:'NEW1',links:[{rel:'payer-action',href:'https://www.sandbox.paypal.com/checkoutnow?token=NEW1'}]}};for(let i=0;i<3;i++)assert.equal((await handleQuoteApi(req('checkout',{method:'POST'}),env,{api})).status,200);assert.equal(creates,1);});
test('ambiguous capture timeout reconciles without a second charge',async()=>{const {env}=await setup();let captureCalls=0,reads=0;const api=async(_env,path,o)=>{if(o?.method==='POST'){captureCalls++;throw Error('PROVIDER_RETRY');}const value=order();if(reads++===0)value.status='APPROVED';return value};assert.equal((await handleQuoteApi(req('capture',{method:'POST'}),env,{api})).status,200);assert.equal(captureCalls,1);assert.equal((await handleQuoteApi(req('capture',{method:'POST'}),env,{api})).status,200);assert.equal(captureCalls,1);});
test('duplicate and out-of-order refund webhooks cannot restore entitlement',async()=>{const {env}=await setup();const h=Object.fromEntries(['auth-algo','cert-url','transmission-id','transmission-sig','transmission-time'].map(n=>['paypal-'+n,'x']));const api=async(_env,path)=>path.includes('verify-webhook')?{verification_status:'SUCCESS'}:order();const post=type=>handleQuoteApi(new Request(origin+'/api/quotes/paypal-webhook',{method:'POST',headers:h,body:JSON.stringify({id:type,event_type:type,resource:{supplementary_data:{related_ids:{order_id:'ORDER1'}}}})}),env,{api});assert.equal((await post('PAYMENT.CAPTURE.REFUNDED')).status,200);assert.equal((await post('PAYMENT.CAPTURE.REFUNDED')).status,200);await post('PAYMENT.CAPTURE.COMPLETED');assert.equal((await env.QUOTE_DB.prepare('SELECT status FROM quotes WHERE id=?').bind(id).first()).status,'refunded');assert.equal((await handleQuoteApi(req('download'),env,{api})).status,403);});
test('no payment mode or missing support contact fails closed',async()=>{const {env}=await setup();delete env.QUOTE_SUPPORT_EMAIL;const r=await handleQuoteApi(req('checkout',{method:'POST'}),env);assert.equal(r.status,503);});
